apiVersion: apps/v1
kind: Deployment
metadata:
  name: manga-api-deplyment
spec:
  selector:
    matchLabels:
      app: manga-api
  template:
    metadata:
      labels:
        app: manga-api
    spec:
      containers:
      - name: manga-api
        image: denixjg/manga-api:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            value: mongodb-service
